<?xml version="1.0"?>
<package format="3">
  <name>voxblox_ros</name>
  <version>0.0.0</version>
  <description>Voxblox ROS interface</description>

  <author email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</author>
  <author email="marius.fehr@mavt.ethz.ch">Marius Fehr</author>

  <maintainer email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</maintainer>
  <maintainer email="marius.fehr@mavt.ethz.ch">Marius Fehr</maintainer>

  <license>BSD</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 1">catkin_simple</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend condition="$ROS_VERSION == 1">cv_bridge</depend>
  <depend condition="$ROS_VERSION == 1">gflags_catkin</depend>
  <depend condition="$ROS_VERSION == 1">interactive_markers</depend>
  <depend condition="$ROS_VERSION == 1">minkindr_conversions</depend>
  <depend condition="$ROS_VERSION == 1">pcl_conversions</depend>
  <depend condition="$ROS_VERSION == 1">pcl_ros</depend>
  <depend condition="$ROS_VERSION == 1">tf</depend>
  <depend>sensor_msgs</depend>
  <depend>voxblox</depend>
  <depend>voxblox_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>std_srvs</depend>
  <depend>minkindr_conversions</depend>

  <depend condition="$ROS_VERSION == 2">gflags</depend>
  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <depend condition="$ROS_VERSION == 2">cv_bridge</depend>
  <depend condition="$ROS_VERSION == 2">tf2_ros</depend>
  <depend condition="$ROS_VERSION == 2">pcl_conversions</depend>
  <depend condition="$ROS_VERSION == 2">image_transport</depend>
  <depend condition="$ROS_VERSION == 2">pcl_ros</depend>
  <depend condition="$ROS_VERSION == 2">tf2_eigen</depend>

</package>
